### ISSUE TITLE
Bug 修复建议

### ISSUE THREAD

**Issue by kinsluck** [Laisky/laisky-blog#120]
在 blog 的预览页面能看到 Html 代码，相当不美观，可以修复吗？
![BUG](https://user-images.githubusercontent.com/17947570/38068690-0db408e2-3345-11e8-9247-7f0654cdd50b.png)

**Comment by Laisky** [comment]
谢谢指出……

某位懒癌晚期患者早就想修了。这个 preview 页有一个构思，然而一年前写了两行后就没有然后了…

**Comment by Laisky** [comment]
@kinsluck 略有些粗暴的修了… 53819bdff11460acdf7cdad18a3b1e6d2e70122c

**Comment by kinsluck** [comment]
看起来好多了👍，希望不要出 bug 。也希望有空能把新出现的问题 markdown 标记也修了😅
