### ISSUE TITLE
post code in wrong font color

### ISSUE THREAD

**Issue by Laisky** [Laisky/laisky-blog#39]
![_ _blog_laisky_com_ _clustering_ _ sklearn clustering](https://cloud.githubusercontent.com/assets/4532436/7697365/9803b8e2-fe39-11e4-8a48-40734ecc77f6.png)

**Comment by observerss** [comment]
你开issue也太认真了orz

有功夫截图画个箭头写点字再上传，都已经修完了吧

**Comment by Laisky** [comment]
@observerss 正在挖另外一个 feature 的大坑，暂时没工夫修

用 skitch ，截图画箭头就三秒钟
